apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "wordpress.labels" . | nindent 4 }}
    component: wordpress
spec:
  selector:
    {{- include "wordpress.selectorLabels" . | nindent 4 }}
    component: wordpress
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
