{{- if .Values.enabled}}
{{- if .Values.createServiceAccount -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: {{ $.Release.Namespace }}
  name:  {{ $.Release.Name }}
  labels:
    {{- include "reliza-watcher.labels" . | nindent 4 }}
{{- end }}
{{- end }}