apiVersion: v2
appVersion: 2.14.0
dependencies:
    - alias: relizapostgresql
      condition: relizapostgresql.enabled
      name: postgresql
      repository: oci://registry.relizahub.com/library
      version: '>=0.1.0'
description: An open source trusted cloud native registry that stores, signs, and scans content
home: https://goharbor.io
icon: https://raw.githubusercontent.com/goharbor/website/main/static/img/logos/harbor-icon-color.png
keywords:
    - docker
    - registry
    - harbor
maintainers:
    - email: yan-yw.wang@broadcom.com
      name: Yan Wang
    - email: wenkai.yin@broadcom.com
      name: Wenkai Yin
    - email: miner.yang@broadcom.com
      name: Miner Yang
    - email: shengwen.yu@broadcom.com
      name: Shengwen Yu
name: harbor-helm
sources:
    - https://github.com/goharbor/harbor
    - https://github.com/goharbor/harbor-helm
version: 1.18.0-reliza.1
# Built by CI on 2025-10-25T11:41:54Z
# Source commit: b329f31a02bd993e83b20f9df3ed778b8066ae48
