# Reliza customization: Add reliza-postgresql as optional dependency
dependencies:
  - name: postgresql
    version: ">=0.1.3"
    repository: oci://registry.relizahub.com/library
    condition: postgresql.enabled
