# K3s Simple Test - ClusterIP with Reliza PostgreSQL
# Minimal configuration for quick testing

# Expose as ClusterIP (access via port-forward)
expose:
  type: clusterIP
  tls:
    enabled: false
  clusterIP:
    name: harbor
    labels: {}
    annotations: {}
    ports:
      httpPort: 80
      httpsPort: 443
  ingress:
    hosts:
      core: ""
    controller: default

externalURL: http://harbor.local

# Admin credentials
harborAdminPassword: "Harbor12345"

# Use Reliza PostgreSQL
relizapostgresql:
  enabled: true
  auth:
    username: harbor
    password: "PostgresTest123"
    database: registry
  primary:
    persistence:
      enabled: true
      size: 5Gi
    resources:
      requests:
        memory: 256Mi
        cpu: 250m
      limits:
        memory: 512Mi
        cpu: 500m

database:
  type: internal
  # Database connection details are automatically configured from relizapostgresql.auth.*
  # No manual configuration needed!

# Minimal storage
persistence:
  enabled: true
  persistentVolumeClaim:
    registry:
      size: 5Gi
    jobservice:
      size: 1Gi
    trivy:
      size: 1Gi

# Minimal resources
core:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

portal:
  replicas: 1
  resources:
    requests:
      memory: 64Mi
      cpu: 50m
    limits:
      memory: 256Mi
      cpu: 250m

jobservice:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

registry:
  replicas: 1
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 512Mi
      cpu: 500m

trivy:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m

chartmuseum:
  enabled: false

notary:
  enabled: false

metrics:
  enabled: false

logLevel: info
