# Copyright Reliza Incorporated. 2019 - 2025. Licensed under the terms of MIT.
# SPDX-License-Identifier: MIT

annotations:
  images: |
    - name: sealed-secrets-controller
      image: registry.relizahub.com/library/sealed-secrets-controller:0.0.2
  licenses: MIT
  tanzuCategory: clusterUtility
apiVersion: v2
appVersion: 0.31.0
dependencies:
- name: reliza-common
  repository: oci://registry.relizahub.com/library
  version: 0.0.1
description: Sealed Secrets are "one-way" encrypted K8s Secrets that can be created
  by anyone, but can only be decrypted by the controller running in the target cluster
  recovering the original object.
home: https://bitnami.com
keywords:
- secrets
- sealed-secrets
kubeVersion: '>=1.16.0-0'
maintainers:
- name: Reliza Incorporated
  url: https://github.com/relizaio
name: sealed-secrets
sources:
- https://github.com/relizaio/helm-charts
- https://github.com/bitnami-labs/sealed-secrets
version: 2.5.20
