{{- if eq .Values.create_secret_in_chart "regular"}}
apiVersion: v1
kind: Secret
metadata:
  name: reliza-cd
  namespace: {{ .Release.Namespace }}
  labels:
    app: reliza-cd
type: Opaque
data:
  URI: {{ .Values.hubUri | b64enc | quote }}
  APIKEYID: {{ .Values.relizaApiId | b64enc | quote }}
  APIKEY: {{ .Values.relizaApiKey | b64enc | quote }}
{{- end }}